name: Build

on:
  push:
    tags:
      - '*'

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format lib test example --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test example

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
